export const mockRentals = [
  {
    id: 1,
    title: "Cozy Studio in East Hollywood",
    address: "4567 Fountain Ave, Los Angeles, CA 90029",
    price: 1500,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    imageUrl: "https://example.com/studio-image.jpg",
    description: "Charming studio apartment with modern amenities, close to public transportation and local cafes.",
    lat: 34.095,
    lng: -118.295,
  },
  {
    id: 2,
    title: "Spacious 2BR near Silver Lake",
    address: "1234 Virgil Ave, Los Angeles, CA 90029",
    price: 2800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    imageUrl: "https://example.com/2br-image.jpg",
    description: "Newly renovated apartment with hardwood floors, in-unit laundry, and a balcony overlooking the city.",
    lat: 34.090,
    lng: -118.287,
  },
  {
    id: 3,
    title: "Vintage 1BR with Character",
    address: "7890 Melrose Hill St, Los Angeles, CA 90029",
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    imageUrl: "https://example.com/vintage-1br-image.jpg",
    description: "Charming 1920s apartment with original details, updated kitchen, and a small private patio.",
    lat: 34.088,
    lng: -118.305,
  },
  {
    id: 4,
    title: "Modern Loft near Thai Town",
    address: "2468 Santa Monica Blvd, Los Angeles, CA 90029",
    price: 2200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    imageUrl: "https://example.com/loft-image.jpg",
    description: "Industrial-style loft with high ceilings, exposed brick, and a fully equipped kitchen. Walking distance to great restaurants.",
    lat: 34.091,
    lng: -118.300,
  },
  {
    id: 5,
    title: "Sunny 3BR Family Home",
    address: "1357 Normal Ave, Los Angeles, CA 90029",
    price: 3500,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    imageUrl: "https://example.com/3br-home-image.jpg",
    description: "Spacious family home with a backyard, garage parking, and recently updated appliances. Close to schools and parks.",
    lat: 34.093,
    lng: -118.291,
  },
];
